name: DNSControl

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: dnscontrol
  cancel-in-progress: false

permissions:
  contents: read
  pull-requests: write

env:
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  INWX_USER: ${{ secrets.INWX_USER }}
  INWX_PASSWORD: ${{ secrets.INWX_PASSWORD }}

jobs:
  dnscontrol:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4.2.1

      - name: Check config
        run: dnscontrol check

      - name: Preview
        if: github.event_name == 'pull_request'
        shell: bash # needed for `bash -o pipefail`
        # Renovate PRs must not change any DNS records to be auto-merged
        run: dnscontrol preview ${{ github.actor == 'renovate[bot]' && '--expect-no-changes' || '' }} | tee preview.txt

      - name: Comment preview on PR
        if: ${{ !cancelled() && github.event_name == 'pull_request' }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          {
            echo '### `dnscontrol preview`'
            echo '```'
            sed 's/\x1b\[[0-9;]*m//g' preview.txt
            echo '```'
          } > comment.md
          gh pr comment "${{ github.event.pull_request.number }}" --edit-last --create-if-none --body-file comment.md

      - name: Push
        if: github.event_name == 'push'
        run: dnscontrol push
